pytest: test that self-signed certificates have `rest-host` IP in Subject Alternative Name.
This fails currently, so next commit fix it up.

Error:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.2', port=40415):
Max retries exceeded with url: /v1/list-methods
(Caused by SSLError(SSLCertVerificationError
(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch,
certificate is not valid for '127.0.0.2'. (_ssl.c:1007)")))
```