pytest: test that clnrest doesn't depend on cln-grpc plugin certificates.
This fails currently, so next commit fix it up.

Error:

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=40917):
Max retries exceeded with url: /v1/list-methods
(Caused by SSLError(SSLCertVerificationError
(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch,
certificate is not valid for '127.0.0.1'. (_ssl.c:1007)")))
```