pytest: update clnrest websocket tests.
This fails currently, so next commit fix it up.

In next commit, we'll change clnrest websocket authorization.  We
do this in order to no longer rely on issue #6725.  Only runes
which authorize the `getinfo` method will be authorized for connecting
with clnrest websocket.

The test `test_clnrest_websocket_rune_no_getinfo` has been modified
accordingly.

The tests `test_clnrest_websocket_rune_readonly` and
`test_clnrest_websocket_rune_getinfo` have been added.

Error:

```
====== short test summary info =====
FAILED tests/test_clnrest.py::test_clnrest_websocket_rune_readonly - assert 0 == 1
FAILED tests/test_clnrest.py::test_clnrest_websocket_rune_getinfo - assert 0 == 1
FAILED tests/test_clnrest.py::test_clnrest_websocket_rune_no_getinfo - assert 1 == 0
```